### ISSUE TITLE
Parameter not working in offline SQS ARN definition

### ISSUE THREAD

**Issue by jaffacake** [svdgraaf/serverless-pseudo-parameters#33]
Hi,

I used your plugin to handle adding in the account ID to my SQS queue ARN, which worked great when deploying. However, when running locally (`serverless offline start`) I get the following error:

```
(node:20672) UnhandledPromiseRejectionWarning: Invalid request: MissingQueryParamRejection(QueueName), MissingFormFieldRejection(QueueUrl): Invalid request: MissingQueryParamRejection(QueueName), MissingFormFieldRejection(QueueUrl); see the SQS docs.
    at Request.extractError (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/Users/xxxx/code/authoriser/node_modules/aws-sdk/lib/event_listeners.js:299:13)
    at IncomingMessage.emit (events.js:194:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:20672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

Here's my ARN line: `- sqs: arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:${self:custom.queueName}`

My temporary fix is to manually switch this to: `- sqs: arn:aws:sqs:${self:provider.region}:xxxx:${self:custom.queueName}`

Would it be possible to have this variable resolve in offline mode? Or at the very least be set to some random string to prevent the error.

Thanks!

**Comment by oba11** [comment]
same here

**Comment by ramses132** [comment]
SAME!!

**Comment by owfm** [comment]
Any update on this?

**Comment by feeh27** [comment]
Same problem

**Comment by medikoo** [comment]
Closing, as all functionalities as provided by this plugin are now covered by the Framework (since v2.50.0)
