### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by caevv** [svdgraaf/serverless-pseudo-parameters#7]
This started happening, and even after removing every parameter, the only fix was to remove the plugin.

```
Cannot convert undefined or null to object

TypeError: Cannot convert undefined or null to object
    at replaceChildNodes (/usr/src/app/node_modules/serverless-pseudo-parameters/lib/index.js:57:14)
    at Object.keys.forEach.identifier (/usr/src/app/node_modules/serverless-pseudo-parameters/lib/index.js:27:50)
    at Array.forEach (native)
    at ServerlessAWSPseudoParameters.addParameters (/usr/src/app/node_modules/serverless-pseudo-parameters/lib/index.js:27:28)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:42:50)
```

**Comment by nils2504** [comment]
Hi, update to 1.3.1 - was a bug in 1.3.0.

**Comment by caevv** [comment]
Thanks for the quick answer, I am using 1.3.1 version.

```
bash-4.4# npm list serverless-pseudo-parameters
`-- serverless-pseudo-parameters@1.3.1
```

**Comment by caevv** [comment]
1.2.0 is good.

**Comment by nils2504** [comment]
any other plugins your using with the serverless framework?

**Comment by caevv** [comment]
No, that's the only one.

**Comment by svdgraaf** [comment]
The stacktrace you are giving, doesn't make any sense for 1.3.1, are you very sure you updated to 1.3.1?
In `1.3.1`, `replaceChildNodes` is on line 61. In `1.3.0` it is on line 57.

I'm going to check whether I actually updated the file correctly to npm, as you make me doubt myself now ;)

Also: can you perhaps post your cloudformation file, or your serverless.yml?

**Comment by svdgraaf** [comment]
UGH. Ok, it probably was my bad! Can you please try again with the latest `1.3.2`?

**Comment by caevv** [comment]
Awesome, working now. Thanks @svdgraaf

**Comment by svdgraaf** [comment]
Awesome, glad to have it resolved quickly ;)
